import { useEffect, useMemo, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { ArrowLeft, BriefcaseBusiness, Camera, Heart, Image as ImageIcon, LoaderCircle, LogOut, QrCode, ScanLine, Search, Send, UserRound, X } from 'lucide-react';
import QRCode from 'qrcode';
import { Html5Qrcode } from 'html5-qrcode';
import { supabase } from './lib/supabase';

type StoreItem = { id:string; name:string; avatar_url?:string|null; address?:string|null; description?:string|null; qr_token:string; lastMessage?:string; updatedAt?:string };
type Message = { id:string; text:string; createdAt:string; photo?:string|null; senderId:string };
type SellerChat = { id:string; buyerId:string; storeId:string; storeName:string; buyerName:string; updatedAt:string };
const SCANNED_KEY='kakasta_scanned_store_ids';
const NAME_KEY='kakasta_display_name';

async function ensureSession(role:'buyer'|'seller', displayName?:string){
  let {data:{session},error:sessionError}=await supabase.auth.getSession();
  if(sessionError)throw sessionError;
  if(!session){const r=await supabase.auth.signInAnonymously();if(r.error)throw r.error;session=r.data.session}
  if(!session?.user)throw new Error('Не удалось создать сессию.');
  const {data:profile,error:profileError}=await supabase.from('profiles').select('display_name').eq('id',session.user.id).maybeSingle();
  if(profileError)throw profileError;
  const requestedName=displayName?.trim(),existingName=(profile?.display_name||'').trim(),name=requestedName||existingName;
  const payload:any={id:session.user.id,role};if(requestedName)payload.display_name=requestedName;
  const {error}=await supabase.from('profiles').upsert(payload);if(error)throw error;
  return {id:session.user.id,displayName:name};
}
function readScannedIds(){try{return JSON.parse(localStorage.getItem(SCANNED_KEY)||'[]') as string[]}catch{return[]}}
function writeScannedIds(ids:string[]){localStorage.setItem(SCANNED_KEY,JSON.stringify([...new Set(ids)]))}

function App(){
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[userId,setUserId]=useState<string|null>(null),[displayName,setDisplayName]=useState(''),[nameDraft,setNameDraft]=useState(localStorage.getItem(NAME_KEY)||''),[stores,setStores]=useState<StoreItem[]>([]),[selected,setSelected]=useState<StoreItem|null>(null),[selectedChatId,setSelectedChatId]=useState<string|null>(null),[search,setSearch]=useState(''),[liked,setLiked]=useState<Record<string,boolean>>({}),[loading,setLoading]=useState(false),[profile,setProfile]=useState(false),[seller,setSeller]=useState(false),[qr,setQr]=useState<StoreItem|null>(null),[scanner,setScanner]=useState(false),[message,setMessage]=useState(''),[messages,setMessages]=useState<Message[]>([]);
 const loadBuyerStores=async()=>{const ids=readScannedIds();if(!ids.length){setStores([]);return}const {data,error:e}=await supabase.from('stores').select('id,name,address,description,avatar_url,qr_token').in('id',ids);if(e)throw e;const rows=(data||[]) as StoreItem[];const missing=ids.filter(id=>!rows.some(r=>r.id===id));if(missing.length)writeScannedIds(ids.filter(id=>!missing.includes(id)));setStores(rows)};
 useEffect(()=>{(async()=>{try{const n=(localStorage.getItem(NAME_KEY)||'').trim();const result=await ensureSession('buyer',n||undefined);setUserId(result.id);setDisplayName(result.displayName);if(result.displayName)localStorage.setItem(NAME_KEY,result.displayName);await loadBuyerStores();setReady(true)}catch(e){setError(e instanceof Error?e.message:'Ошибка подключения.');setReady(true)}})()},[]);
 const filtered=useMemo(()=>stores.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())),[stores,search]);
 const openStore=async(store:StoreItem)=>{if(!userId||loading)return false;setLoading(true);try{const found=await supabase.from('chats').select('id').eq('store_id',store.id).eq('buyer_id',userId).order('created_at',{ascending:false}).limit(1).maybeSingle();if(found.error)throw found.error;let chat=found.data;if(!chat){const c=await supabase.from('chats').insert({store_id:store.id,buyer_id:userId}).select('id').single();if(c.error)throw c.error;chat=c.data}const r=await supabase.from('messages').select('id,text,photo_url,created_at,sender_id').eq('chat_id',chat.id).order('created_at',{ascending:true});if(r.error)throw r.error;const loaded=(r.data||[]).map((m:any)=>({id:m.id,text:m.text||'',photo:m.photo_url,createdAt:m.created_at,senderId:m.sender_id}));setSelected(store);setSelectedChatId(chat.id);setMessages(loaded);return true}catch(e){setError(e instanceof Error?e.message:'Не удалось открыть чат.');return false}finally{setLoading(false)}};
 const send=async()=>{const text=message.trim();if(!text||!userId||!selectedChatId)return;setMessage('');const r=await supabase.from('messages').insert({chat_id:selectedChatId,sender_id:userId,text}).select('id,text,photo_url,created_at,sender_id').single();if(r.error){setMessage(text);setError(r.error.message);return}setMessages(c=>[...c,{id:r.data.id,text:r.data.text||'',photo:r.data.photo_url,createdAt:r.data.created_at,senderId:r.data.sender_id}]);await supabase.from('chats').update({updated_at:new Date().toISOString()}).eq('id',selectedChatId)};
 const scanResult=async(decoded:string)=>{const token=decoded.startsWith('kakasta:store:')?decoded.slice('kakasta:store:'.length):decoded.trim();if(!token)return;const r=await supabase.from('stores').select('id,name,address,description,avatar_url,qr_token').eq('qr_token',token).maybeSingle();if(r.error){setError(r.error.message);return}if(!r.data){setError('Этот QR-код контакта не найден.');return}const store=r.data as StoreItem;writeScannedIds([store.id,...readScannedIds()]);setStores(c=>c.some(x=>x.id===store.id)?c:[store,...c]);setScanner(false);const opened=await openStore(store);if(!opened){setScanner(false)}};
 useEffect(()=>{if(!scanner)return;const reader=new Html5Qrcode('qr-reader');let stopped=false;reader.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},async(decoded)=>{if(stopped)return;stopped=true;await reader.stop().catch(()=>undefined);await scanResult(decoded)},()=>undefined).catch(e=>setError(e instanceof Error?e.message:'Не удалось открыть камеру.'));return()=>{stopped=true;reader.stop().catch(()=>undefined)}},[scanner]);
 useEffect(()=>{if(!selectedChatId)return;let alive=true;const toMessage=(m:any):Message=>({id:m.id,text:m.text||'',photo:m.photo_url,createdAt:m.created_at,senderId:m.sender_id});const add=(m:any)=>setMessages(c=>c.some(x=>x.id===m.id)?c:[...c,toMessage(m)]);const refresh=async()=>{const r=await supabase.from('messages').select('id,text,photo_url,created_at,sender_id').eq('chat_id',selectedChatId).order('created_at',{ascending:true});if(alive&&!r.error)setMessages((r.data||[]).map(toMessage))};const ch=supabase.channel('kakasta-chat-'+selectedChatId).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'chat_id=eq.'+selectedChatId},p=>add(p.new)).subscribe();const timer=window.setInterval(refresh,1200);return()=>{alive=false;window.clearInterval(timer);supabase.removeChannel(ch)}},[selectedChatId]);
 const enterSeller=async()=>{try{setLoading(true);const result=await ensureSession('seller');setUserId(result.id);setDisplayName(result.displayName);setSeller(true)}catch(e){setError(e instanceof Error?e.message:'Не удалось открыть кабинет продавца.')}finally{setLoading(false)}};
 const logoutSeller=async()=>{setLoading(true);try{const result=await ensureSession('buyer');setUserId(result.id);setDisplayName(result.displayName);setSeller(false);setSelected(null);setSelectedChatId(null);setMessages([]);await loadBuyerStores()}catch(e){setError(e instanceof Error?e.message:'Не удалось выйти из кабинета.')}finally{setLoading(false)}};
 if(!ready)return <main className="app"><div className="loading"><LoaderCircle className="spin"/><b>{error||'Подключаем…'}</b></div></main>;
 if(!displayName)return <main className="app nameScreen"><div className="nameCard"><div className="nameIcon"><UserRound/></div><h1>Как вас называть?</h1><p>Введите имя или название, под которым вас будут видеть.</p><input autoFocus value={nameDraft} onChange={e=>setNameDraft(e.target.value)} onKeyDown={async e=>{if(e.key==='Enter'&&nameDraft.trim()){try{const n=nameDraft.trim();const result=await ensureSession('buyer',n);localStorage.setItem(NAME_KEY,n);setDisplayName(result.displayName);setUserId(result.id);await loadBuyerStores()}catch(err){setError(err instanceof Error?err.message:'Не удалось сохранить имя.')}}}} placeholder="Ваше имя"/><button disabled={!nameDraft.trim()} onClick={async()=>{try{const n=nameDraft.trim();const result=await ensureSession('buyer',n);localStorage.setItem(NAME_KEY,n);setDisplayName(result.displayName);setUserId(result.id);await loadBuyerStores()}catch(err){setError(err instanceof Error?err.message:'Не удалось сохранить имя.')}}}>Продолжить</button></div></main>;
 if(selected)return <Chat store={selected} messages={messages} message={message} setMessage={setMessage} send={send} back={()=>{setSelected(null);setSelectedChatId(null);setMessages([])}} userId={userId||''}/>;
 if(seller)return <><Seller userId={userId||''} displayName={displayName} onBack={()=>setSeller(false)} onLogout={logoutSeller} onQr={setQr}/>{qr&&<QrModal store={qr} onClose={()=>setQr(null)}/>}</>;
 return <main className="app"><div className="sun sun1"/><div className="sun sun2"/><header><div><b>Деловые чаты</b><span>{displayName}</span></div><button className="icon" onClick={enterSeller} aria-label="Моя страница"><UserRound/></button></header><section className="hero"><h1>С кем вы общаетесь</h1><p>Здесь люди и организации, чьи QR-коды вы отсканировали.</p></section><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск" autoComplete="off"/></div><div className="actions"><button onClick={()=>setScanner(true)}><ScanLine/> Сканировать QR</button></div><section className="cards">{filtered.map(store=><article className="card" key={store.id} onClick={()=>openStore(store)}><div className="avatar">{store.avatar_url?<img src={store.avatar_url} alt=""/>:<BriefcaseBusiness/>}</div><div className="cardbody"><strong>{store.name}</strong><span>Открыть чат</span></div><button className={liked[store.id]?'heart active':'heart'} onClick={e=>{e.stopPropagation();setLiked(v=>({...v,[store.id]:!v[store.id]}))}} aria-label="Добавить в избранное"><Heart fill={liked[store.id]?'currentColor':'none'}/></button></article>)}{!filtered.length&&<div className="emptyCard"><BriefcaseBusiness/><b>Контактов пока нет</b><span>Отсканируйте QR-код человека или организации, чтобы добавить контакт.</span></div>}</section>{profile&&<Modal onClose={()=>setProfile(false)} title="Профиль"><p>Покупатель</p><p className="muted">Магазины добавляются только после сканирования их QR-кода.</p></Modal>}{qr&&<QrModal store={qr} onClose={()=>setQr(null)}/>} {scanner&&<Modal onClose={()=>setScanner(false)} title="Сканировать QR"><div id="qr-reader"/><p className="muted">Наведите камеру на QR-код человека или организации.</p></Modal>}{error&&<button className="errorToast" onClick={()=>setError('')}>{error}<span>×</span></button>}{loading&&<div className="loading"><LoaderCircle className="spin"/><b>Подключаем…</b></div>}</main>
}

function Chat({store,messages,message,setMessage,send,back,userId}:{store:StoreItem;messages:Message[];message:string;setMessage:(v:string)=>void;send:()=>void;back:()=>void;userId:string}){return <main className="chat"><header><button className="icon" onClick={back} aria-label="Назад"><ArrowLeft/></button><div><b>{store.name}</b><span>{store.address||'Деловой контакт'}</span></div><Heart/></header><div className="messages">{messages.map(m=><div className={m.senderId===userId?'bubble mine':'bubble'} key={m.id}><span>{m.text}</span><small>{new Date(m.createdAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div>)}</div><div className="composer"><label><Camera/></label><label><ImageIcon/></label><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Сообщение…"/><button onClick={send} aria-label="Отправить"><Send/></button></div></main>}

function Seller({userId,displayName,onBack,onLogout,onQr}:{userId:string;displayName:string;onBack:()=>void;onLogout:()=>void;onQr:(s:StoreItem)=>void}){
 const [store,setStore]=useState<StoreItem|null>(null),[settings,setSettings]=useState(false),[description,setDescription]=useState(''),[avatarBusy,setAvatarBusy]=useState(false),[chats,setChats]=useState<SellerChat[]>([]),[active,setActive]=useState<SellerChat|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState('');
 const load=async()=>{setBusy(true);const own=await supabase.from('stores').select('id,name,address,avatar_url,qr_token').eq('owner_id',userId).order('created_at',{ascending:true}).limit(1).maybeSingle();if(own.error){setError(own.error.message);setBusy(false);return}let current=own.data as StoreItem|null;if(!current){const c=await supabase.from('stores').insert({owner_id:userId,name:displayName,address:'',description:''}).select('id,name,address,avatar_url,qr_token').single();if(c.error){setError(c.error.message);setBusy(false);return}current=c.data as StoreItem}setStore(current);const list=await supabase.from('chats').select('id,buyer_id,store_id,updated_at,stores!inner(name)').eq('store_id',current.id).order('updated_at',{ascending:false});if(list.error){setError(list.error.message);setBusy(false);return}const chatRows=list.data||[];const buyerIds=[...new Set(chatRows.map((c:any)=>c.buyer_id))];let names:Record<string,string>={};if(buyerIds.length){const pr=await supabase.from('profiles').select('id,display_name').in('id',buyerIds);if(!pr.error)for(const p of pr.data||[])names[p.id]=p.display_name||'Без имени'}setChats(chatRows.map((c:any)=>({id:c.id,buyerId:c.buyer_id,storeId:c.store_id,storeName:c.stores?.name||current!.name,buyerName:names[c.buyer_id]||'Без имени',updatedAt:c.updated_at})));setBusy(false)};
 useEffect(()=>{void load()},[userId]);
 const saveDescription=async()=>{if(!store)return;const v=description.trim();const r=await supabase.from('stores').update({description:v}).eq('id',store.id);if(r.error){setError(r.error.message);return}setStore({...store,description:v});setSettings(false)};
 const uploadAvatar=async(file:File)=>{if(!store)return;setAvatarBusy(true);try{const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=userId+'/'+Date.now()+'.'+ext;const up=await supabase.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type});if(up.error)throw up.error;const url=supabase.storage.from('avatars').getPublicUrl(path).data.publicUrl;const r=await supabase.from('stores').update({avatar_url:url}).eq('id',store.id);if(r.error)throw r.error;setStore({...store,avatar_url:url})}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить аватар.')}finally{setAvatarBusy(false)}};
 const loadMessages=async(chatId:string)=>{const r=await supabase.from('messages').select('id,text,photo_url,created_at,sender_id').eq('chat_id',chatId).order('created_at',{ascending:true});if(r.error){setError(r.error.message);return}setMessages((r.data||[]).map((m:any)=>({id:m.id,text:m.text||'',photo:m.photo_url,createdAt:m.created_at,senderId:m.sender_id})))};
 useEffect(()=>{
   if(!active)return;
   let alive=true;
   const toMessage=(m:any):Message=>({id:m.id,text:m.text||'',photo:m.photo_url,createdAt:m.created_at,senderId:m.sender_id});
   const add=(m:any)=>setMessages(c=>c.some(x=>x.id===m.id)?c:[...c,toMessage(m)]);
   const refreshActiveChat=async()=>{
     const r=await supabase.from('messages').select('id,text,photo_url,created_at,sender_id').eq('chat_id',active.id).order('created_at',{ascending:true});
     if(alive&&!r.error)setMessages((r.data||[]).map(toMessage));
   };
   void refreshActiveChat();
   const ch=supabase.channel('kakasta-seller-chat-'+active.id)
     .on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'chat_id=eq.'+active.id},p=>add(p.new))
     .subscribe();
   const timer=window.setInterval(refreshActiveChat,1200);
   return()=>{alive=false;window.clearInterval(timer);supabase.removeChannel(ch)};
 },[active?.id]);
 const send=async()=>{if(!text.trim()||!active)return;const value=text.trim();setText('');const r=await supabase.from('messages').insert({chat_id:active.id,sender_id:userId,text:value}).select('id,text,photo_url,created_at,sender_id').single();if(r.error){setText(value);setError(r.error.message);return}setMessages(c=>c.some(m=>m.id===r.data.id)?c:[...c,{id:r.data.id,text:r.data.text||'',photo:r.data.photo_url,createdAt:r.data.created_at,senderId:r.data.sender_id}]);await supabase.from('chats').update({updated_at:new Date().toISOString()}).eq('id',active.id)};
 if(busy)return <main className="seller"><div className="loading"><LoaderCircle className="spin"/><b>Открываем кабинет…</b></div></main>;
 if(settings&&store)return <main className="seller"><header><button className="icon" onClick={()=>setSettings(false)} aria-label="Назад"><ArrowLeft/></button><div><b>Настройка страницы</b><span>{store.name}</span></div></header><div className="settingsCard"><div className="profileAvatarLarge">{store.avatar_url?<img src={store.avatar_url} alt=""/>:<UserRound/>}</div><label className="uploadButton"><Camera/> {avatarBusy?'Загрузка…':'Изменить аватар'}<input type="file" accept="image/*" hidden disabled={avatarBusy} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadAvatar(file);e.currentTarget.value=''}}/></label><label className="fieldLabel">Что вы предлагаете</label><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Например: ремонт техники, доставка, консультации, услуги…" maxLength={500}/><button className="saveButton" onClick={()=>void saveDescription()}>Сохранить</button></div>{error&&<button className="errorToast" onClick={()=>setError('')}>{error}<span>×</span></button>}</main>;
 if(active)return <main className="seller"><header><button className="icon" onClick={()=>setActive(null)} aria-label="Назад"><ArrowLeft/></button><div><b>{active.buyerName}</b><span>{active.storeName}</span></div><button className="icon" onClick={onLogout} aria-label="Выйти"><LogOut/></button></header><div className="messages">{messages.map(m=><div className={m.senderId===userId?'bubble mine':'bubble'} key={m.id}><span>{m.text}</span><small>{new Date(m.createdAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div>)}</div><div className="composer"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Сообщение…"/><button onClick={send} aria-label="Отправить"><Send/></button></div>{error&&<button className="errorToast" onClick={()=>setError('')}>{error}<span>×</span></button>}</main>;
 return <main className="seller"><header><div className="sellerHeaderIdentity"><div className="profileAvatarSmall">{store?.avatar_url?<img src={store.avatar_url} alt=""/>:<BriefcaseBusiness/>}</div><div><b>Моя страница</b></div></div><button className="icon" onClick={onBack} aria-label="Назад"><ArrowLeft style={{transform:"rotate(180deg)"}}/></button></header><div className="sellerEmpty"><h2>{store?.name}</h2>{store?.description&&<p className="offerText">{store.description}</p>}<button className="editProfileButton" onClick={()=>{setDescription(store?.description||'');setSettings(true)}}><UserRound/> Изменить страницу</button>{store&&<button className="showQrButton" onClick={()=>onQr(store)}><QrCode/> Показать мой QR-код</button>}<h3>Входящие деловые чаты</h3>{!chats.length?<p>Новых сообщений пока нет. Человек или организация появится здесь после сканирования вашего QR-кода.</p>:<div className="sellerChats">{chats.map(c=><button key={c.id} className="sellerChat" onClick={()=>{setActive(c);setMessages([]);void loadMessages(c.id)}}><span>{c.buyerName}</span><small>{new Date(c.updatedAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></button>)}</div>}</div>{error&&<button className="errorToast" onClick={()=>setError('')}>{error}<span>×</span></button>}</main>
}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="overlay"><div className="modal"><button className="close" onClick={onClose} aria-label="Закрыть"><X/></button><h2>{title}</h2>{children}</div></div>}
function QrModal({store,onClose}:{store:StoreItem;onClose:()=>void}){const [qrUrl,setQrUrl]=useState('');const [qrError,setQrError]=useState('');useEffect(()=>{let alive=true;setQrUrl('');setQrError('');if(!store.qr_token){setQrError('QR-код пока не готов. Попробуйте открыть его ещё раз.');return}QRCode.toDataURL('kakasta:store:'+store.qr_token,{width:320,margin:2,errorCorrectionLevel:'M'}).then(url=>{if(alive)setQrUrl(url)}).catch(()=>{if(alive)setQrError('Не удалось сформировать QR-код. Попробуйте ещё раз.')});return()=>{alive=false}},[store.qr_token]);return <Modal title="Мой QR-код" onClose={onClose}>{qrUrl?<img className="qrImage" src={qrUrl} alt="QR-код для добавления контакта"/>:<div className="qrLoading"><LoaderCircle className="spin"/></div>}{qrError&&<p className="muted">{qrError}</p>}<strong className="qrname">{store.name}</strong><p className="muted">Отсканируйте этот QR-код, чтобы добавить меня в деловые контакты и начать чат.</p></Modal>}
export default App;
